const enDict = {
  "Aram Isai Orozco Soto | Portafolio": "Aram Isai Orozco Soto | Portfolio",
  "Sobre mí": "About me",
  "Estudios": "Studies",
  "Habilidades": "Skills",
  "Experiencia": "Experience",
  "Proyectos": "Projects",
  "Contacto": "Contact",
  "Hola, soy": "Hello, I am",
  "Aram Isai": "Aram Isai",
  "Orozco Soto": "Orozco Soto",
  "Ingeniero en Sistemas Electrónicos Inteligentes": "Intelligent Electronic Systems Engineer",
  "Técnico en Automatización y Integración Industrial · Desarrollador": "Industrial Automation and Integration Technician · Developer",
  "Apasionado por la electrónica inteligente, los sistemas embebidos y el desarrollo de software. Con experiencia práctica en automatización industrial y conocimientos académicos en SEI. Actualmente cursando la carrera en la": "Passionate about smart electronics, embedded systems, and software development. With practical experience in industrial automation and academic knowledge in SEI. Currently studying at",
  "Universidad Autónoma de Ciudad Juárez": "Autonomous University of Ciudad Juarez",
  "Cd. Juárez, Chih.": "Juarez City, Chih.",
  "UACJ · SEI": "UACJ · IES",
  "Inglés B2": "English B2",
  "23 años": "23 years old",
  "Ver Proyectos": "View Projects",
  "Contáctame": "Contact me",
  "Disponible": "Available",
  "Scroll": "Scroll",
  "Formación": "Education",
  "Trayectoria": "Trajectory",
  "Académica": "Academic",
  "Ingeniería en Sistemas Electrónicos Inteligentes (SEI)": "Intelligent Electronic Systems Engineering (IES)",
  "Universidad Autónoma de Ciudad Juárez (UACJ)": "Autonomous University of Ciudad Juarez (UACJ)",
  "En curso": "In progress",
  "2022 – Actualidad · 3 años completados": "2022 - Present · 3 years completed",
  "Carrera enfocada en la implementación de sistemas electrónicos inteligentes para la solución a problemas complejos de la ingeniería, aplicando la electrónica, diseño de semiconductores, desarrollo de software, inteligencia artificial, la electromovilidad, Internet de las cosas y tecnologías emergentes.": "Degree focused on the implementation of intelligent electronic systems to solve complex engineering problems, applying electronics, semiconductor design, software development, artificial intelligence, electromobility, Internet of Things, and emerging technologies.",
  "Sistemas Embebidos": "Embedded Systems",
  "Electrónica Analógica y Digital": "Analog and Digital Electronics",
  "Programación Avanzada": "Advanced Programming",
  "Machine Learning": "Machine Learning",
  "Diseño de Circuitos": "Circuit Design",
  "Matemática para IA": "Mathematics for AI",
  "Automatización": "Automation",
  "Preparatoria": "High School",
  "Ciudad Juárez, Chihuahua": "Juarez City, Chihuahua",
  "Completado": "Completed",
  "2017 - 2020": "2017 - 2020",
  "Formación media superior con orientación hacia ciencias exactas e ingeniería.": "High school education oriented towards exact sciences and engineering.",
  "Capacidades": "Capabilities",
  "Técnicas": "Technical",
  "Programación": "Programming",
  "Web Full Stack": "Full Stack Web",
  "HTML · CSS · JavaScript": "HTML · CSS · JavaScript",
  "Lenguajes de Propósito General": "General Purpose Languages",
  "C · C++ · Python · MATLAB": "C · C++ · Python · MATLAB",
  "Embebido & Hardware": "Embedded & Hardware",
  "MicroPython · Ensamblador · NumPy · VHDL": "MicroPython · Assembly · NumPy · VHDL",
  "Microprocesadores": "Microprocessors",
  "Implementación y programación directa sobre hardware": "Direct hardware programming and implementation",
  "Integración Hardware/Software": "Hardware/Software Integration",
  "Electrónica y lógica de control": "Electronics and control logic",
  "Programación de Microcontroladores": "Microcontroller Programming",
  "Ensamblador · Microcontroladores PIC · ESP32": "Assembly · PIC Microcontrollers · ESP32",
  "Modelos Clasificadores": "Classifier Models",
  "Implementación en Python (Pandas, PyTorch, NumPy)": "Implementation in Python (Pandas, PyTorch, NumPy)",
  "Modelos Predictivos": "Predictive Models",
  "Análisis y predicción de conjuntos de datos": "Data set analysis and prediction",
  "Álgebra Lineal Aplicada": "Applied Linear Algebra",
  "Base matemática para IA": "Mathematical foundation for AI",
  "Electrónica Analógica & Digital": "Analog & Digital Electronics",
  "Sistemas y Circuitos Digitales": "Digital Systems and Circuits",
  "Diseño y simulación de sistemas lógicos · Lógica binaria · Aplicación de álgebra booleana": "Design and simulation of logic systems · Binary logic · Application of Boolean algebra",
  "VHDL": "VHDL",
  "Programación y diseño de hardware en FPGA": "Hardware design and programming in FPGA",
  "Electrónica Básica": "Basic Electronics",
  "Uso de componentes electrónicos y diseño de circuitos para prácticas académicas": "Use of electronic components and circuit design for academic practices",
  "Automatización Industrial": "Industrial Automation",
  "Gabinetes Eléctricos y de Control": "Electrical and Control Cabinets",
  "Construcción, armado y cableado": "Construction, assembly, and wiring",
  "Sistemas Neumáticos y Mecánicos": "Pneumatic and Mechanical Systems",
  "Ensamblaje e integración de maquinaria para sector maquilador": "Assembly and integration of machinery for the manufacturing sector",
  "Diagnóstico de Fallas": "Fault Diagnosis",
  "Detección y corrección técnica en el área industrial": "Technical detection and correction in the industrial area",
  "Competencias": "Competencies",
  "Resolución de Problemas": "Problem Solving",
  "Pensamiento lógico y analítico": "Logical and analytical thinking",
  "Trabajo en Equipo": "Teamwork",
  "Adaptabilidad en entornos industriales": "Adaptability in industrial environments",
  "Idiomas": "Languages",
  "Español (Nativo) · Inglés (B2)": "Spanish (Native) · English (B2)",
  "Laboral": "Work",
  "Técnico en Automatización e Integración Industrial": "Automation and Industrial Integration Technician",
  "Durol Sistemas y Servicios, S.A. de C.V. · Ciudad Juárez, Chihuahua": "Durol Sistemas y Servicios, S.A. de C.V. · Juarez City, Chihuahua",
  "7 meses · Actualidad": "7 months · Present",
  "1 año": "1 year",
  "Activo": "Active",
  "Concluido": "Completed",
  "Participación activa en el diseño y fabricación de maquinaria y líneas de producción para la industria maquiladora de la región.": "Active participation in the design and manufacture of machinery and production lines for the regional manufacturing industry.",
  "Construcción, armado y cableado de gabinetes eléctricos": "Construction, assembly, and wiring of electrical cabinets",
  "Interpretación y análisis de diagramas eléctricos": "Interpretation and analysis of electrical diagrams",
  "Ensamblaje de sistemas eléctricos y neumáticos": "Assembly of electrical and pneumatic systems",
  "Fabricación de maquinaria para industria maquiladora": "Manufacture of machinery for the manufacturing industry",
  "Diagnóstico, detección y corrección de fallas técnicas": "Diagnosis, detection, and correction of technical faults",
  "Uso de herramientas especializadas en automatización industrial": "Use of specialized tools for industrial automation",
  "Programación de PLC básico": "Basic PLC programming",
  "Portafolio": "Portfolio",
  "Realizados": "Completed",
  "Todos": "All",
  "Software": "Software",
  "Hardware / Electrónica": "Hardware / Electronics",
  "IA & ML": "AI & ML",
  "Portafolio Web Interactivo": "Interactive Web Portfolio",
  "Desarrollo de un portafolio web interactivo con diseño responsivo, modo oscuro y soporte bilingüe (Español/Inglés).": "Development of an interactive web portfolio with responsive design, dark mode, and bilingual support (Spanish/English).",
  "Académico · Personal": "Academic · Personal",
  "Candado Electrónico": "Electronic Padlock",
  "Sistema de simulación de candado electrónico implementado con microcontrolador. Gestión de contraseñas y acceso controlado mediante lógica embebida en C++.": "Electronic padlock simulation system implemented with a microcontroller. Password management and controlled access via embedded C++ logic.",
  "Académico": "Academic",
  "Gestor de Contraseñas": "Password Manager",
  "Sistema de almacenamiento seguro de contraseñas en C++. Implementa estructuras de datos para la gestión eficiente de credenciales.": "Secure password storage system in C++. Implements data structures for efficient credential management.",
  "Electrónica": "Electronics",
  "Diodos": "Diodes",
  "Pedal de Distorsión": "Distortion Pedal",
  "Diseño y construcción de un pedal de distorsión para guitarra utilizando diodos. Proyecto de electrónica analógica con aplicación musical.": "Design and construction of a guitar distortion pedal using diodes. Analog electronics project with musical application.",
  "FPGA": "FPGA",
  "Basys3": "Basys3",
  "Lógica Digital en VHDL": "Digital Logic in VHDL",
  "Desarrollo de programas de lógica digital con uso de tarjeta FPGA modelo Basys3. Diseño de circuitos combinacionales y secuenciales para la demostración práctica y comprensión.": "Development of digital logic programs using a Basys3 model FPGA board. Design of combinational and sequential circuits for practical demonstration and understanding.",
  "Diseño de programas con ESP32 y electrónica analógica": "Design of programs with ESP32 and analog electronics",
  "Programas de lógica matemática implementados sobre microprocesadores empleando MicroPython para control, procesamiento numérico con uso de interfaces programadas vía HTML y uso de bibliotecas como FLASK y similares.": "Mathematical logic programs implemented on microprocessors using MicroPython for control, numerical processing using interfaces programmed via HTML, and the use of libraries like FLASK and similar.",
  "Ensamblador": "Assembly",
  "Hardware": "Hardware",
  "Programas en Ensamblador": "Assembly Programs",
  "Desarrollo de programas básicos en lenguaje ensamblador para control y comprensión profunda del hardware a bajo nivel para la demostración práctica y de comprensión básica del lenguaje.": "Development of basic programs in assembly language for control and deep understanding of the hardware at a low level for practical demonstration and basic understanding of the language.",
  "Python": "Python",
  "Modelos de ML": "ML Models",
  "Implementación de clasificadores y modelos predictivos de datos usando Python. Aplicación de técnicas de Machine Learning para análisis y predicción.": "Implementation of data classifiers and predictive models using Python. Application of Machine Learning techniques for analysis and prediction.",
  "¿Trabajamos juntos?": "Work together?",
  "Hoy": "Today",
  "Estoy abierto a oportunidades laborales y colaboraciones. Contáctame y te responderé lo más pronto posible.": "I am open to job opportunities and collaborations. Contact me and I will respond as soon as possible.",
  "Ubicación": "Location",
  "Ciudad Juárez, Chihuahua, México": "Juarez City, Chihuahua, Mexico",
  "Universidad": "University",
  "UACJ – Ingeniería en SEI": "UACJ - IES Engineering",
  "Empresa Actual": "Current Company",
  "Durol Systems": "Durol Systems",
  "Correo Personal": "Personal Email",
  "Correo Universitario": "University Email",
  "Teléfono": "Phone",
  "Nombre completo *": "Full name *",
  "Correo electrónico *": "Email *",
  "Asunto *": "Subject *",
  "Mensaje *": "Message *",
  "Enviar Mensaje": "Send Message",
  "Tu nombre": "Your name",
  "tu@correo.com": "you@email.com",
  "¿En qué puedo ayudarte?": "How can I help you?",
  "Escribe tu mensaje aquí...": "Write your message here...",
  "© 2025 Aram Isai Orozco Soto · Todos los derechos reservados.": "© 2025 Aram Isai Orozco Soto · All rights reserved.",
  "Descargar CV": "Download Resume",
  "Ver CV Web": "View Web CV",
  "Ver CV": "View Resume",
  "¿Quieres ver mi perfil completo?": "Want to see my full profile?",
  "Descarga mi currículum vitae en formato PDF para conocer más detalles sobre mi trayectoria y habilidades.": "Download my resume in PDF format to learn more about my background and skills.",
  "Puedes consultar mi currículum interactivo en versión web o descargarlo en formato PDF.": "You can view my interactive web resume or download it as a PDF.",
  "Puedes consultar mi currículum interactivo en versión web y exportarlo a PDF desde allí.": "You can view my interactive web resume and export it to PDF from there.",
  "Descargar CV (PDF)": "Download Resume (PDF)",
  "Perfil de LinkedIn": "LinkedIn Profile",
  "Repositorio de GitHub": "GitHub Repository",
  "Perfil de Indeed": "Indeed Profile"
};